cache:
  directories:
    - _build
    - deps
language: elixir
matrix:
  include:
    - elixir: 1.7.1
      otp_release: 21.0
    - elixir: 1.6.5
      otp_release: 20.1
    - elixir: 1.5.3
      otp_release: 20.1
sudo: false
script:
- mix test
- mix dialyzer
