cache:
  directories:
    - _build
    - deps
language: elixir
matrix:
  include:
    - elixir: 1.5.2
      otp_release: 20.1
    - elixir: 1.4.5
      otp_release: 19.3
    - elixir: 1.3.4
      otp_release: 19.3
    - elixir: 1.2.6
      otp_release: 18.3
    - elixir: 1.1.1
      otp_release: 18.3
sudo: false
script:
- mix test
- mix dialyzer
